conky.config = {
    alignment  = 'middle_left',
    background = true,

    own_window = true,
    own_window_type = 'override',
    own_window_transparent = true,
    own_window_hints = 'undecorated.below,sticky,skip_taskbar,skip_pager',

    font = 'Myrica M:bold:size=15',
    default_color = 'white',
    color0 = '99dd99',
    color1 = 'white',
    color2 = '929292',

    double_buffer = true,
    border_width = 0,
    update_interval = 1.0,
    cpu_avg_samples = 2,
    use_xft = true,
}

conky.text = [[
 ${goto 10}
       $nodename ${sysname} ${machine}
  $sysname $kernel $machine
 $hr
       ${time %Y年 %m月 %d日 %a曜日}
           ${time %k:%M:%S}
 $hr
  Frequency (in GHz):${freq_g}
  CPU Usage: ${cpu cpu1}%
  CPU Usage: ${cpu cpu2}%
  CPU Usage: ${cpu cpu3}%
  CPU Usage: ${cpu cpu4}%
  CPU Usage: ${cpu cpu5}%
  CPU Usage: ${cpu cpu6}%
  CPU Usage: ${cpu cpu7}%
  CPU Usage: ${cpu cpu8}%
  RAM Usage: ${memperc}%
 $membar
 $hr
 Signal: ${wireless_link_qual wlp46s0}% ${wireless_link_bar 10 wlp46s0}
 Rate: ${wireless_bitrate wlp46s0}
 IP: ${addrs wlp46s0}
 Down speed ${downspeed wlp46s0}/s${alignr} Up speed ${upspeed wlp46s0}/s
 Down total ${totaldown wlp46s0}${alignr}Up total ${totalup wlp46s0}
 $hr
 Name              PID   CPU%   MEM%
 ${top name 1} ${top pid 1} ${top cpu 1} ${top mem 1}
 ${top name 2} ${top pid 2} ${top cpu 2} ${top mem 2}
 ${top name 3} ${top pid 3} ${top cpu 3} ${top mem 3}
 ${top name 4} ${top pid 4} ${top cpu 4} ${top mem 4}
 ${top name 5} ${top pid 5} ${top cpu 5} ${top mem 5}
 $hr
  File systems:
   / ${fs_free /}/${fs_size /}
 ${fs_bar 6 /}
]]
