# tmuxを256色表示できるようにする
set -g default-terminal "xterm-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

# status-rightの設定
set-option -g status-right '#( \
  label="%m月%d日 %a曜日 %p %I:%M"; \
  bg=color238; \
  color=color255; \
  text_fg=color255; \
  echo "$label"; \
)'

set-option -g pane-border-style "fg=#FFFFFF"
set-option -g pane-active-border-style "fg=#00FF00"

# ステータスバーをボトムに配置する
set-option -g status-position bottom

# 左右のステータスバーの長さを決定する
set-option -g status-left-length 90
set-option -g status-right-length 90

# センタライズ（主にウィンドウ番号など）
set-option -g status-justify centre

# ボーダーラインの線種変更
set -g pane-border-lines heavy

# ステータスバーの色を設定する
set-option -g status-bg "color238"

# status line の文字色を指定する。
set-option -g status-fg "color255"

# ペインの移動2
# Shift + 上下左右でペインを移動できるようにする。(<Prefix>不要)
# 行頭に"bind -n"をつけるとPrefixが不要になる。
bind -n S-left select-pane -L
bind -n S-down select-pane -D
bind -n S-up select-pane -U
bind -n S-right select-pane -R

# vimのキーバインドでペインをリサイズする
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# | でペインを縦分割する
bind | split-window -h

# - でペインを縦分割する
bind - split-window -v

# 番号基準値を変更
set-option -g base-index 1

# マウス操作を有効にする
set-option -g mouse on
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'copy-mode -e'"
