[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'tokorom/vim-swift-format'
hook_source = '''
source ~/.vim/plugins/vim-swift-format.vim
'''

[[plugins]]
repo = 'tyru/caw.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_source = '''
source ~/.vim/plugins/lightline.vim
'''

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'hrsh7th/vim-vsnip'

[[plugins]]
repo = 'hrsh7th/vim-vsnip-integ'

[[plugins]]
repo = 'h1mesuke/vim-alignta'

[[plugins]]
repo = 'osyo-manga/vim-anzu'
hook_source = '''
source ~/.vim/plugins/anzu.vim
'''

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_source = '''
source ~/.vim/plugins/vim-easymotion.vim
'''

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_source = '''
source ~/.vim/plugins/vim-indent-guides.vim
'''

[[plugins]]
repo = 'kana/vim-operator-replace'

[[plugins]]
repo = 'rhysd/vim-operator-surround'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_source = '''
source ~/.vim/plugins/vim-quickrun.vim
'''

[[plugins]]
repo = 'kana/vim-smartinput'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'szw/vim-tags'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'LeafCage/yankround.vim'
hook_source = '''
source ~/.vim/plugins/yankround.vim
'''
