[[plugins]]
repo = 'mattn/ctrlp-matchfuzzy'
depends = ['Ctrlp']
hook_source = '''
source ~/.config/nvim/plugins/ctrlp-matchfuzzy.vim
'''

[[plugins]]
repo = 'junegunn/fzf.vim'
on_cmd = ['FZFToggle']
hook_source = '''
source ~/.config/nvim/plugins/fzf.vim
'''

[[plugins]]
repo = 'sjl/gundo.vim'
on_cmd = ['GundoToggle']
hook_source = '''
source ~/.config/nvim/gundo.vim
'''

[[plugins]]
repo = 'majutsushi/tagbar'
on_cmd = ['TagbarToggle']
hook_source = '''
source ~/.config/nvim/tagbar.vim
'''

[[plugins]]
repo = 'gko/vim-coloresque'
on_ft = 'css'
