[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'mileszs/ack.vim'

[[plugins]]
repo = 'basyura/bitly.vim'

[[plugins]]
repo = 'tyru/caw.vim'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
source ~/.config/nvim/plugins/denite.vim
'''

[[plugins]]
repo = 'vim-scripts/fcitx.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
source ~/.config/nvim/plugins/lightline.vim
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'kannokanno/previm'
hook_add = '''
source ~/.config/nvim/plugins/previm.vim
'''

[[plugins]]
repo = 'basyura/TweetVim'
hook_add = '''
source ~/.config/nvim/plugins/tweetvim.vim
'''

[[plugins]]
repo = 'basyura/twibill.vim'

[[plugins]]
repo = 'h1mesuke/vim-alignta'

[[plugins]]
repo = 'osyo-manga/vim-anzu'
hook_add = '''
source ~/.config/nvim/plugins/anzu.vim
'''

[[plugins]]
repo = 'lordm/vim-browser-reload-linux'

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
source ~/.config/nvim/plugins/vim-easymotion.vim
'''

[[plugins]]
repo = "airblade/vim-gitgutter"

[[plugins]]
repo = "tpope/vim-fugitive"

[[plugins]]
repo = 'cohama/vim-hier'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
source ~/.config/nvim/plugins/vim-indent-guides.vim
'''

[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'kana/vim-operator-replace'

[[plugins]]
repo = 'rhysd/vim-operator-surround'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
source ~/.config/nvim/plugins/vim-quickrun.vim
'''

[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo = 'kana/vim-smartinput'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'szw/vim-tags'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'LeafCage/yankround.vim'
hook_add = '''
source ~/.config/nvim/plugins/yankround.vim
'''
