[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'mfussenegger/nvim-dap'
hook_add = 'source ~/.config/nvim/plugins/nvim-dap.lua'

[[plugins]]
repo = 'rcarriga/nvim-dap-ui'

[[plugins]]
repo = 'mussenegger/nvim-dap-python'

[[plugins]]
repo = 'rafamadriz/friendly-snippets'

[[plugins]]
repo = 'tyru/caw.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_source = '''
source ~/.config/nvim/plugins/lightline.vim
'''

[[plugins]]
repo = 'williamboman/mason.nvim'
hook_add = 'source ~/.config/nvim/plugins/mason.lua'

[[plugins]]
repo = 'hrsh7th/vim-vsnip'

[[plugins]]
repo = 'hrsh7th/vim-vsnip-integ'

[[plugins]]
repo = 'h1mesuke/vim-alignta'

[[plugins]]
repo = 'osyo-manga/vim-anzu'
hook_source = '''
source ~/.config/nvim/plugins/anzu.vim
'''

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_source = '''
source ~/.config/nvim/plugins/vim-easymotion.vim
'''

[[plugins]]
repo = 'preservim/vim-indent-guides'
hook_source = '''
source ~/.config/nvim/plugins/vim-indent-guides.vim
'''

[[plugins]]
repo = 'kana/vim-operator-replace'

[[plugins]]
repo = 'rhysd/vim-operator-surround'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_source = '''
set splitbelow
set splitright
nnoremap <leader>r :QuickRun<CR>
let g:quickrun_config={}
let g:quickrun_config._={
  \  "outputter" : "buffer",
  \  "outputter/buffer/opener": "5new",
  \  'outputter/buffer/close_on_empty': 1,
  \  'hook/animation/enable': 1,
  \ }
'''

[[plugins]]
repo = 'kana/vim-smartinput'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'szw/vim-tags'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'LeafCage/yankround.vim'
hook_source = '''
source ~/.config/nvim/plugins/yankround.vim
'''
