[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'Shougo/ddc.vim'
hook_source = '''
source ~/.config/nvim/plugins/ddc.vim
'''

[[plugins]]
repo = 'Shougo/ddc-around'

[[plugins]]
repo = 'LumaKernel/ddc-file'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'

[[plugins]]
repo = 'Shougo/ddc-converter_remove_overlap'

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]
repo = 'theblob42/drex.nvim'

[[plugins]]
repo = 'tyru/caw.vim'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_source = '''
source ~/.config/nvim/plugins/lightline.vim
'''

[[plugins]]
repo = 'mfussenegger/nvim-dap'

[[plugins]]
repo = 'Shougo/pum.vim'
hook_source = '''
source ~/.config/nvim/plugins/pum.vim
'''

[[plugins]]
repo = 'h1mesuke/vim-alignta'

[[plugins]]
repo = 'osyo-manga/vim-anzu'
hook_source = '''
source ~/.config/nvim/plugins/anzu.vim
'''

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_source = '''
source ~/.config/nvim/plugins/vim-indent-guides.vim
'''

[[plugins]]
repo = 'kana/vim-operator-replace'

[[plugins]]
repo = 'rhysd/vim-operator-surround'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_source = '''
source ~/.config/nvim/plugins/vim-quickrun.vim
'''

[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'kana/vim-smartinput'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'szw/vim-tags'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'LeafCage/yankround.vim'
hook_source = '''
source ~/.config/nvim/plugins/yankround.vim
'''
